FROM python:3.9.9-slim-buster
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
COPY worker/requirements.txt /code/requirements.txt
RUN pip install --upgrade pip && pip install -r /code/requirements.txt
COPY worker/ /code/
WORKDIR /code
ENTRYPOINT ["python", "rabbit_consumer.py"]