services:

  rabbitmq:
    image: 'rabbitmq:3.9.16-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    env_file:
      - ./config/.env

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./config/.env

  app:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./:/code
    env_file:
      - ./config/.env

  api:
    build: .
    volumes:
      - ./:/code
    env_file:
      - ./config/.env
    ports:
      - '8000:8000'
    command: python3 api/main.py

  adm_panel:
    build:
      context: .
      dockerfile: Dockerfile_adm_panel
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    env_file:
      - ./config/.env
    depends_on:
      - db

  worker_ap:
    build:
      context: .
      dockerfile: Dockerfile_worker_ap
    stdin_open: true
    tty: true
    env_file:
      - ./config/.env
    depends_on:
      - rabbitmq
