FROM python:3.9.9-slim-buster
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
COPY worker/ /code/
RUN pip install --upgrade pip && pip install -r /code/requirements.txt
WORKDIR /code
ENTRYPOINT ["python", "rabbit_consumer.py"]