# Generated by Django 3.2 on 2022-05-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_template', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Mailing',
        ),
    ]
