# Generated by Django 3.2 on 2022-05-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_template', '0002_rename_contact_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='mail_schedule',
            field=models.CharField(choices=[('Once', 'Once'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=255),
        ),
    ]
